name: DL_GENOMICS
channels:
  - pytorch
dependencies:
  - python
  - jupyter
  - numpy  
  - pandas
  - matplotlib
  - pytorch
  - seaborn
  - pandas
  - tqdm
  - pip
  - pip:
    - scikit-learn
    - scikit-learn-extra
    - scipy